### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by wexom** [kevinkk525/OC-GUI-API#2]
Hi. I found bug in your code in GUI.lua at line 67 
is:                     local a_w,a_w=component.screen.getAspectRatio()
should be:        local a_w,a_h=component.screen.getAspectRatio()

**Comment by kevinkk525** [comment]
Thanks for reporting that. I did not put much effort into that function. does it work with the change?

**Comment by wexom** [comment]
Yes, it work perfect ;)

**Comment by kevinkk525** [comment]
I'm glad to hear that. Thanks for reporting this issue!
